name: mdns_dart
description: A comprehensive mDNS (Multicast DNS) service discovery and advertisement library for Dart, ported from HashiCorp Go implementation.
version: 2.0.1
homepage: https://github.com/animeshxd/mdns_dart
repository: https://github.com/animeshxd/mdns_dart
topics:
  - mdns
  - dns
  - service-discovery
  - multicast
  - networking

environment:
  sdk: ^3.0.0

# No external dependencies - pure Dart implementation
dependencies:

dev_dependencies:
  lints: '>=3.0.0'
  test: '>=1.25.5'
