name: mdns_dart
description: A comprehensive mDNS (Multicast DNS) service discovery library for Dart, ported from HashiCorp Go implementation.
version: 1.0.3
homepage: https://github.com/animeshxd/mdns_dart
repository: https://github.com/animeshxd/mdns_dart
topics:
  - mdns
  - dns
  - service-discovery
  - multicast
  - networking

environment:
  sdk: ^3.8.0

# No external dependencies - pure Dart implementation
dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
